### ISSUE TITLE
Restore to meraki firmware

### ISSUE THREAD

**Issue by ghost** [riptidewave93/Openwrt-Z1#3]
Not really an issue, just a question if anybody knows how to restore the original firmware from meraki, the original partition with the firmware is still on the meraki

**Comment by riptidewave93** [comment]
While this isn't documented, the process CAN be done. You just need to boot into the OpenWRT initramfs image (flash an initramfs build to the kernel partition, and reboot the device). Once here, you can then modify the UBI partitions to restore the original storage, and rootfs partitions from stock as well as remove the rootfs and rootfs_data made by OpenWRT. Once done, re-flashing the stock kernel to the kernel partition should restore the stock OS. If you don't have the stock files, or need more of a tutorial, I can try to get one written up somewhere. I am just not sure of the legalities of posting direct links to the stock firmware files.

**Comment by lowe493** [comment]
Thanks for replying, ive emailed you on the email listed on your profile :+1:
